# Global Conan configuration (installed into $CONAN_HOME/global.conf)
core:default_profile=linux-gcc-release
core:default_build_profile=linux-gcc-release
core.download:parallel=4
core.sources:download_cache=
tools.cmake.cmaketoolchain:generator=Ninja
tools.build:jobs={{ os.cpu_count() }}
